Update build_test_push_docker_fp_X86_arm_version_aware.yaml

diff --git a/.github/workflows/build_test_push_docker_fp_X86_arm_version_aware.yaml b/.github/workflows/build_test_push_docker_fp_X86_arm_version_aware.yaml
--- a/.github/workflows/build_test_push_docker_fp_X86_arm_version_aware.yaml
+++ b/.github/workflows/build_test_push_docker_fp_X86_arm_version_aware.yaml
@@ -23,7 +23,6 @@ jobs:
     outputs:
       build_fp: ${{ steps.changes.outputs.build_fp }}
       fp_version: ${{ steps.changes.outputs.fp_version }}
-
     steps:
     - name: Checkout code
       uses: actions/checkout@v4
@@ -190,17 +189,17 @@ jobs:
           fi
           
           BUILD_FLAGS=$(echo "$BUILD_FLAGS" | sed 's/^ *//')  
-          cd $GITHUB_WORKSPACE/executions
       
           sed -i -e "s/\${TAG}/$TAG/g" -e "s/\${BUILD_ARGS}/$BUILD_FLAGS/g" \
-            execution_gp_arm_docker_buildNtester.json
+            $GITHUB_WORKSPACE/executions/execution_gp_arm_docker_buildNtester.json
           
           echo "Generated execution file:"
           cat execution_gp_arm_docker_buildNtester.json
-          
+          cp $GITHUB_WORKSPACE/executions/execution_gp_arm_docker_buildNtester.json $GITHUB_WORKSPACE/ngen-datastream/research_datastream/terraform/test/execution_gp_arm_docker_buildNtester.json
+          cd $GITHUB_WORKSPACE/ngen-datastream/research_datastream/terraform
           echo "Building with TAG: $TAG and FLAGS: $BUILD_FLAGS"
-          execution_arn=$(aws stepfunctions start-execution --state-machine-arn $(cat $GITHUB_WORKSPACE/ngen-datastream/research_datastream/terraform_community/sm_ARN.txt) --name docker_builder_$(env TZ=US/Eastern date +'%Y%m%d%H%M%S') --input "file://$GITHUB_WORKSPACE/executions/execution_gp_arm_docker_buildNtester.json" --region us-east-1 --query 'executionArn' --output text); echo "Execution ARN: $execution_arn"; status="RUNNING"; while [ "$status" != "SUCCEEDED" ]; do status=$(aws stepfunctions describe-execution --execution-arn "$execution_arn" --region us-east-1 --query 'status' --output text); echo "Current status: $status"; if [ "$status" == "FAILED" ]; then echo "State machine execution failed!"; exit 1; fi; sleep 5; done; echo "State machine execution succeeded!"
-
+          execution_arn=$(aws stepfunctions start-execution --state-machine-arn $(cat ./sm_ARN.txt) --name docker_builder_$(env TZ=US/Eastern date +'%Y%m%d%H%M%S') --input "file://test/execution_gp_arm_docker_buildNtester.json" --region us-east-1 --query 'executionArn' --output text); echo "Execution ARN: $execution_arn"; status="RUNNING"; while [ "$status" != "SUCCEEDED" ]; do status=$(aws stepfunctions describe-execution --execution-arn "$execution_arn" --region us-east-1 --query 'status' --output text); echo "Current status: $status"; if [ "$status" == "FAILED" ]; then echo "State machine execution failed!"; exit 1; fi; sleep 5; done; echo "State machine execution succeeded!"
+      
       - name: Tear down infra
         if: always()
         run: |
